### ISSUE TITLE
Node.js detection warning persists despite valid installation and positive isNpxInstalled test

### ISSUE THREAD

**Issue by JeanYalJean** [JetBrains/mcp-server-plugin#1]
After installing the MCP Server plugin in IntelliJ IDEA, I can successfully use the plugin's features with Claude integration to read file information. However, on every IDE startup, I consistently receive a popup warning stating "MCP Server Proxy requires Node.js to be installed", despite having a valid Node.js installation.

### Node.js Installation Verification
Terminal commands verify that Node.js is properly installed:
- `which npx` returns: `/Users/walker/.nvm/versions/node/v23.4.0/bin/npx`
- `node -v` and `npm -v` both return expected versions

### Initial Troubleshooting
I've attempted the following steps without success:
- Reinstalling the plugin
- Restarting the plugin

### Code Investigation
Suspecting an issue with the `isNpxInstalled` method, I:
1. Cloned the mcp-server-plugin repository
2. Created a simple test case using AI assistance (due to limited Kotlin experience)
3. Test results showed `isNpxInstalled` returns `true`

This suggests a potential disconnect between the method's behavior and the plugin's Node.js detection logic.

## Environment
- IDE: IntelliJ IDEA 2024.3 (Ultimate Edition)
- MCP Server Version: 1.0.6
- Operating System: macOS 14.1 (M3 MAX)
- NVM Version: 0.40.1
- Node.js Version: v23.4.0
- NPM Version: 10.9.2
- PNPM Version: 9.15.0

![image](https://github.com/user-attachments/assets/ed6596c8-46ee-4da9-9966-d1e62314cb4c)

Please advise on potential solutions or if additional debugging information is needed.

**Comment by MaXal** [comment]
I've added an action to all notifications to avoid showing them again. The update will be soon available.
